var searchData=
[
  ['generic_5futilities_2esql_5fin',['generic_utilities.sql_in',['../generic__utilities_8sql__in.html',1,'']]],
  ['gettingstarted_2edox',['gettingstarted.dox',['../gettingstarted_8dox.html',1,'']]],
  ['grid_5fsearch_2esql_5fin',['grid_search.sql_in',['../grid__search_8sql__in.html',1,'']]],
  ['grid_5fsearch_5fkmeans_5fall',['grid_search_kmeans_all',['../grid__search_8sql__in.html#a40317b533b263c5161b9a58ca465844a',1,'grid_search.sql_in']]],
  ['generic_20utilities',['Generic Utilities',['../group__grp__genutils.html',1,'']]],
  ['glob_20_28pseudofunction_29',['glob (Pseudofunction)',['../group__grp__glob.html',1,'']]],
  ['grid_20search',['Grid Search',['../group__grp__grid__search.html',1,'']]],
  ['gs_5felasticnet_5fcv',['gs_elasticnet_cv',['../grid__search_8sql__in.html#a5eaa06cba07e1e21a26713237747ddd7',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds, boolean standardize, text optimizer, text optimizer_params, text excluded, integer max_iter, float8 tolerance):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a8a4d2cef78ec1eaea3869a32b1538d20',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds, boolean standardize, text optimizer, text optimizer_params, text excluded, integer max_iter):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a2a710743fd7fa89e07e6996e85f4ec18',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds, boolean standardize, text optimizer, text optimizer_params, text excluded):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a5654f6238aa56e16f2cb8d96ea87603f',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds, boolean standardize, text optimizer, text optimizer_params):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#aba7930e45d44255b8ce6cc45af3b6a62',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds, boolean standardize, text optimizer):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a80f6935687c2dc39481124e568a67dcc',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds, boolean standardize):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#abcc3c6e888203b9c73a5f8be5c3bda44',1,'gs_elasticnet_cv(text tbl_source, text tbl_result, text col_dep_var, text col_ind_var, text regress_family, float8[] alphas, float8[] lambdas, text id_column, text mdl_table, int k_folds):&#160;grid_search.sql_in']]],
  ['gs_5fkmeans_5frandom',['gs_kmeans_random',['../grid__search_8sql__in.html#aa690c748a2368c82b502bec1b57da732',1,'gs_kmeans_random(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist, text agg_centroid, integer max_num_iterations, float8 min_frac_reassigned):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a406e8bc856187cbaa7c54c5504089d06',1,'gs_kmeans_random(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;, text agg_centroid=&quot;avg&quot;, integer max_num_iterations=20):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a104f0d06d256ebfcac772ac1bb28b373',1,'gs_kmeans_random(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;, text agg_centroid=&quot;avg&quot;):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a08320c9fbfc6143eb024d919bad1df0c',1,'gs_kmeans_random(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#afc16de168f0784d669ed2907b08c1ec9',1,'gs_kmeans_random(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point):&#160;grid_search.sql_in']]],
  ['gs_5fkmeanspp',['gs_kmeanspp',['../grid__search_8sql__in.html#a6bd7f538fe1a49f1c63584d060f503ea',1,'gs_kmeanspp(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist, text agg_centroid, integer max_num_iterations, float8 min_frac_reassigned, float8 seeding_sample_ratio):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#aa4aedae87f6db43d48ea920733e528e6',1,'gs_kmeanspp(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;, text agg_centroid=&quot;avg&quot;, integer max_num_iterations=20, float8 min_frac_reassigned=0.001):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a12e07aa3846f381e1a01c80c977e9b79',1,'gs_kmeanspp(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;, text agg_centroid=&quot;avg&quot;, integer max_num_iterations=20):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a83179efcf8bd9149a4b458ae10d6f3e1',1,'gs_kmeanspp(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;, text agg_centroid=&quot;avg&quot;):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#a904ad3d22c77ce9775622a328cdb660e',1,'gs_kmeanspp(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point, text fn_dist=&quot;squared_dist_norm2&quot;):&#160;grid_search.sql_in'],['../grid__search_8sql__in.html#af98aafed3fb87b240e219cb1a3217e63',1,'gs_kmeanspp(text id_column, text mdl_output_tbl, int[] num_clusters_arr, text rel_source, text expr_point):&#160;grid_search.sql_in']]]
];
